### ISSUE TITLE
seed ="dnhhnbdfnfduy"  secret not correctly reconstructed

### ISSUE THREAD

**Issue by yujingyue9166** [unicredit/mosaic#1]
I try to go run  -tags=z3,miracl examples/ex_GoAPI_noservice_noz3.go. When the seed is not empty, the decryption result is not right. I wonder how to use this code.

**Comment by marcellop71** [comment]
please see https://github.com/marcellop71/mosaic/issues/2#issuecomment-727608217

**Comment by yujingyue9166** [comment]
Thank you very much.
